[package]
name = "showman-data-derive"
version = "0.1.0"
authors = ["Gianluca <gianluca.brian@hotmail.it>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.12"
quote = "1.0.4"
syn = "1.0.18"